name: Generate

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Platane /snk@master
      id: snake-gif
      with:
        github_user_name: CristinaPineda
        svg_out_path: dist/github-contribution-grid-snake.svg

